### ISSUE TITLE
Error running setup_project.zsh

### ISSUE THREAD

**Issue by jrvidotti** [benlawraus/anvil_works_design_test#2]
Hey there!

Had a crash here:

```
make scripts executable ..
Copy server and client files (running git_pull_from_anvil_works.zsh..
No arguments supplied. Using:
     /home/junior/anvil/uplink/my_project/AnvilWorksApp
     /home/junior/anvil/uplink/my_project
Copying laptop files into backup directory before syncing.
cp: cannot stat '/home/junior/anvil/uplink/my_project/server_code': No such file or directory
cp: cannot stat '/home/junior/anvil/uplink/my_project/client_code': No such file or directory
Git pull the anvil.works app..
Enter passphrase for key '/home/junior/.ssh/id_rsa': 
From ssh://anvil.works:2222/AWWAZ7OBMZSOCBTV
 * branch            master     -> FETCH_HEAD
Already up to date.
Copy anvil app code to project directories..
building file list ... done
created directory /home/junior/anvil/uplink/my_project/server_code
./
AnexosModule.py
ClientesModule.py
EmpresasModule.py
ProdutosModule.py
SolicitacoesModule.py
StatusModule.py
UserModule.py
requirements.txt
Utils/
Utils/__init__.py

sent 15.152 bytes  received 263 bytes  30.830,00 bytes/sec
total size is 14.413  speedup is 0,93
Regenerating _anvil_designer.py files in client_code..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_files.py", line 28, in <module>
    if yaml2classes():
       ^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_files.py", line 19, in yaml2classes
    file_string = yaml2definition(parsed, form_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 346, in yaml2definition
    derive_dict(parsed, catalog, form_name, import_list, form_name)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 267, in derive_dict
    derive_dict(component, catalog, parent, import_list, form_name)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 267, in derive_dict
    derive_dict(component, catalog, parent, import_list, form_name)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 277, in derive_dict
    catalog[name] = lowest_level_component(value, parent, import_list, form_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 227, in lowest_level_component
    attrs = add_properties(value, parent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 150, in add_properties
    validate_yaml(value, 'properties')
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 99, in validate_yaml
    validate_yaml(value[sequence_key], key)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 103, in validate_yaml
    value.revalidate(sy.EmptyList())
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/representation.py", line 109, in revalidate
    result = schema(self._chunk)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/scalar.py", line 27, in __call__
    chunk.expect_scalar(self.rule_description)
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/yamllocation.py", line 125, in expect_scalar
    self.expecting_but_found(
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/yamllocation.py", line 44, in expecting_but_found
    raise YAMLValidationError(
strictyaml.exceptions.YAMLValidationError: when expecting a emptylist
  in "<unicode string>", line 11, column 1:
        properties:
    ^ (line: 11)
found a mapping
  in "<unicode string>", line 34, column 1:
          icon: fa:paperclip
    ^ (line: 34)
git pull completed.
If the database schema has changed, run yaml2schema.zsh
Generate all the _anvil_designer.py files for every form.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_files.py", line 28, in <module>
    if yaml2classes():
       ^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_files.py", line 19, in yaml2classes
    file_string = yaml2definition(parsed, form_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 346, in yaml2definition
    derive_dict(parsed, catalog, form_name, import_list, form_name)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 267, in derive_dict
    derive_dict(component, catalog, parent, import_list, form_name)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 267, in derive_dict
    derive_dict(component, catalog, parent, import_list, form_name)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 277, in derive_dict
    catalog[name] = lowest_level_component(value, parent, import_list, form_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 227, in lowest_level_component
    attrs = add_properties(value, parent)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 150, in add_properties
    validate_yaml(value, 'properties')
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 99, in validate_yaml
    validate_yaml(value[sequence_key], key)
  File "/home/junior/anvil/uplink/my_project/_anvil_designer/generate_class.py", line 103, in validate_yaml
    value.revalidate(sy.EmptyList())
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/representation.py", line 109, in revalidate
    result = schema(self._chunk)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/scalar.py", line 27, in __call__
    chunk.expect_scalar(self.rule_description)
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/yamllocation.py", line 125, in expect_scalar
    self.expecting_but_found(
  File "/home/junior/anvil/uplink/my_project/venv/lib/python3.11/site-packages/strictyaml/yamllocation.py", line 44, in expecting_but_found
    raise YAMLValidationError(
strictyaml.exceptions.YAMLValidationError: when expecting a emptylist
  in "<unicode string>", line 11, column 1:
        properties:
    ^ (line: 11)
found a mapping
  in "<unicode string>", line 34, column 1:
          icon: fa:paperclip
    ^ (line: 34)
Crashed while regenerating the _anvil_designer.py files.
```

My form_template.yaml:
```
container:
  type: ColumnPanel
  properties: {col_widths: '{"SWPKZM":50}'}
components:
- type: ColumnPanel
  properties: {col_widths: '{"EZXAFF":60,"XWBHIZ":15}'}
  name: column_panel_1
  layout_properties: {grid_position: 'QFSUQZ,SWPKZM'}
  components:
  - type: FileLoader
    properties:
      role: null
      show_state: true
      align: center
      tooltip: ''
      border: ''
      file_types: .png,.jpeg,.jpg
      enabled: true
      files: []
      foreground: ''
      visible: true
      text: Anexo
      font_size: null
      font: ''
      spacing_above: small
      icon_align: left
      spacing_below: small
      italic: false
      file: null
      background: ''
      bold: false
      underline: false
      multiple: false
      icon: fa:paperclip
    name: fl_anexo
    layout_properties:
      col_widths: {}
      grid_position: XOJOYE,XWBHIZ
  - type: TextBox
    properties: {}
    name: inp_comentario
    layout_properties:
      col_widths: {}
      grid_position: XOJOYE,EZXAFF
    event_bindings: {pressed_enter: inp_comentario_pressed_enter}
is_package: true
```

**Comment by benlawraus** [comment]
In _anvil_designer > generate_class.py

Can you comment out line 150: 
validate_yaml(value, 'properties')

And run it again? Maybe it will generate an adequate _anvil_designer.py file….
regards
Ben
P.S. I really regret using the strict_yaml package !

**Comment by benlawraus** [comment]
I changed the error to a warning.
